/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package nl.toefel.kotlin.html.dsl

import kotlin.test.Test
import kotlin.test.assertTrue

class DSLTest {
    @Test
    fun testAppHasAGreeting() {
        val attributesAsMap = mapOf("a" to "b")
        val doc = html {
            body {
                div {
                    +"hoi"
                    +"sua"
                }
                div {
                    a {
                        // use property syntax, requires a kotlin field property for each property
                        href = "chef"

                        // to is an infix operator provided by Tag, more flexible but less readable
                        "target" to "_blank"

                        // infix operator allows application of map
                        attributesAsMap.forEach {
                            it.key to it.value
                        }

                        // + is a unaryOperator, which creates a text content.
                        +"linkje"
                    }
                }
                span { +"inside span" }
            }
        }

        val renderedHtml = doc.toString()
        println(doc.toString())

        assertTrue { renderedHtml.contains("<html>") }
        assertTrue { renderedHtml.contains("<div>") }
        assertTrue { renderedHtml.contains("<span>") }
        assertTrue { renderedHtml.contains("<a") }
        assertTrue { renderedHtml.contains("a=\"b\"") }
        assertTrue { renderedHtml.contains("href=\"chef\"") }
        assertTrue { renderedHtml.contains("target=\"_blank\"") }
        assertTrue { renderedHtml.contains("linkje") }
    }
}
