/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package nl.toefel.kotlin.html

import nl.toefel.kotlin.html.dsl.html


fun main(args: Array<String>) {
    val defaultAttributes = mapOf("a" to "b")
    val doc = html {
        body {
            div {
                +"hoi"
                +"sua"
            }
            div {
                a {
                    defaultAttributes.forEach{
                        it.key to it.value
                    }
                    // custom attributes

                    "href" to "blaat"
                    +"linkje"
                }
            }
            span { +"inside span" }
        }
    }

    println(doc.toString())
}
