/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package nl.toefel.kotlin.html

import nl.toefel.kotlin.html.dsl.html


fun main(args: Array<String>) {
    val defaultAttributes = mapOf("a" to "b")
    val doc = html {
        body {
            div {
                +"hoi"
                +"sua"
            }
            div {
                a {
                    // use property syntax, requires a kotlin field property for each property
                    href = "chef"

                    // to is an infix operator provided by Tag, more flexible but less readable
                    "target" to "_blank"

                    // infix operator allows application of map
                    defaultAttributes.forEach {
                        it.key to it.value
                    }

                    // + is a unaryOperator, which creates a text content.
                    +"linkje"
                }
            }
            span { +"inside span" }
        }
    }

    println(doc.toString())
}
